spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/example?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 50
  batch:
    job:
      name: productMonthlyAggregationJob
    jdbc:
      initialize-schema: always
